#SERVER
SERVER_PORT: 8081
ACTIVE_PROFILE: prod

#DATABASE VARIABLE
MYSQL_DATABASE: railway
MYSQLHOST: monorail.proxy.rlwy.net
MYSQLPORT: 10417
MYSQLUSER: root
MYSQL_ROOT_PASSWORD: eECdc-a46h63Ha31fCd3654AC1gBFhA2

#SECURITY TOKEN KEYS
ACCESS_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/access-token-private-key
ACCESS_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/access-token-public-key
REFRESH_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/refresh-token-private-key
REFRESH_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/refresh-token-public-key